name: Build gallery manifest

on:
  push:
    paths:
      - 'assets/foto/**'
      - '.github/workflows/build-gallery.yml'
  workflow_dispatch:

permissions:
  contents: write   # даём Actions право пушить

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true   # чтобы работал git push

      - name: Generate assets/gallery.json
        run: |
          python3 - <<'PY'
          import os, json, re, pathlib

          folder = pathlib.Path("assets/foto")
          files = [f.name for f in folder.iterdir() if f.is_file() and not f.name.startswith(".")]

          # естественная сортировка: 1,2,10 вместо 1,10,2
          def key(s):
              parts = re.split(r'(\d+)', s)
              return [int(p) if p.isdigit() else p.lower() for p in parts]
          files.sort(key=key)

          out = [f"assets/foto/{name}" for name in files]
          (pathlib.Path("assets") / "gallery.json").write_text(
              json.dumps(out, ensure_ascii=False, indent=2)
          )
          PY

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/gallery.json
          if ! git diff --cached --quiet; then
            git commit -m "Build gallery manifest"
            git push
          else
            echo "No changes."
            fi
